version: "3"

services:
  esp-updater:
    image: slaesh/esp-updater
    container_name: esp-updater
    restart: unless-stopped
    ports:
      - 35982:35982
    volumes:
      - ./fw:/fw:rw

    logging:
      driver: gcplogs
      options: # https://docs.docker.com/config/containers/logging/gcplogs/
        gcp-project: srv-slaesh
        gcp-meta-zone: west1
        gcp-meta-name: srv.slae.sh
